#!/usr/bin/env python3
from subprocess import Popen, PIPE
from time import sleep
import datetime

p = Popen(['xinput', 'test-xi2', '--root'], stdout=PIPE, encoding='utf-8')
try:
	count = 0
	print('Waiting for clicks...')
	while True:
		l = p.stdout.readline().strip()
		if not l.endswith('(RawButtonPress)'):
			continue

		while True:
			l = p.stdout.readline().strip()
			if not l.startswith('detail:'):
				continue

			detail = int(l.split()[-1])
			if not detail == 1:
				continue

			now = datetime.datetime.now()
			path = f'screenshots/{now.isoformat()}.png'
			print(f'Saving screenshot to {path}')

			Popen(['import', '-window', 'root', path])
			count += 1

			break
except KeyboardInterrupt:
	p.kill()
	print(f'Saved a total of {count} screenshots.')
